---
    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: davita-kafka-kafka-bootstrap
      namespace: curlnoistio
    spec:
      host: "*.svc.cluster.local"
      trafficPolicy:
        tls:
          mode: DISABLE