---
apiVersion: v1
data:
  cert1: {{ .Values.ingressgateway.tls.crt}}
  key1: {{ .Values.ingressgateway.tls.key}}
kind: Secret
metadata:
  name: istio-ingressgateway-certs
  namespace: {{ .Values.ingressgateway.namespace }}
type: Opaque